project_new de10-nano-nanorv32-wb-soc-qqspi_0 -overwrite
set_global_assignment -name FAMILY "Cyclone V"
set_global_assignment -name DEVICE 5CSEBA6U23I7
set_global_assignment -name TOP_LEVEL_ENTITY de10_nano_nanorv32_wb_soc
set_global_assignment -name VERILOG_FILE src/altera_clkgen_0/wrapped_altpll.v
set_global_assignment -name VERILOG_FILE src/altera_clkgen_0/altpll_wb_clkgen.v
set_global_assignment -name VERILOG_FILE src/altera_clkgen_0/wrapped_altera_pll.v
set_global_assignment -name VERILOG_FILE src/altera_clkgen_0/altera_pll_wb_clkgen.v
set_global_assignment -name VERILOG_FILE ../src/gpio/gpio.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_aligner.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_alu.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_bufreg.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_bufreg2.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_compdec.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_csr.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_ctrl.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_debug.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_decode.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_immdec.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_mem_if.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_rf_if.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_rf_ram_if.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_rf_ram.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_rf_top.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_state.v
set_global_assignment -name VERILOG_FILE ../src/serv/serv_top.v
set_global_assignment -name VERILOG_FILE ../src/servile/servile_arbiter.v
set_global_assignment -name VERILOG_FILE ../src/servile/servile_mux.v
set_global_assignment -name VERILOG_FILE ../src/servile/servile_rf_mem_if.v
set_global_assignment -name VERILOG_FILE ../src/servile/servile_rf.v
set_global_assignment -name VERILOG_FILE ../src/servile/servile.v
set_global_assignment -name VERILOG_FILE ../src/wb_timer/nanorv32_timer.v
set_global_assignment -name VERILOG_FILE ../src/wb_timer/wb_timer.v
set_global_assignment -name VERILOG_FILE ../src/uart16550/raminfr.v
set_global_assignment -name VERILOG_FILE ../src/uart16550/uart_receiver.v
set_global_assignment -name VERILOG_FILE ../src/uart16550/uart_regs.v
set_global_assignment -name VERILOG_FILE ../src/uart16550/uart_rfifo.v
set_global_assignment -name VERILOG_FILE ../src/uart16550/uart_sync_flops.v
set_global_assignment -name VERILOG_FILE ../src/uart16550/uart_tfifo.v
set_global_assignment -name VERILOG_FILE ../src/uart16550/uart_top.v
set_global_assignment -name VERILOG_FILE ../src/uart16550/uart_transmitter.v
set_global_assignment -name VERILOG_FILE ../src/uart16550/uart_wb.v
set_global_assignment -name VERILOG_FILE ../src/verilog-arbiter/arbiter.v
set_global_assignment -name VERILOG_FILE ../src/wb_qqspi/wb_qqspi.v
set_global_assignment -name VERILOG_FILE ../src/wb_qqspi/qqspi.v
set_global_assignment -name VERILOG_FILE ../src/wb_intercon/wb_cdc.v
set_global_assignment -name VERILOG_FILE ../src/wb_intercon/wb_arbiter.v
set_global_assignment -name VERILOG_FILE ../src/wb_intercon/wb_data_resize.v
set_global_assignment -name VERILOG_FILE ../src/wb_intercon/wb_mux.v
set_global_assignment -name VERILOG_FILE ../src/serv_soc_wb/serv_soc_wb.v
set_global_assignment -name VERILOG_FILE ../src/serv_soc_wb/wb_intercon.v
set_global_assignment -name VERILOG_FILE src/de10-nano-nanorv32-wb-soc-qqspi_0/rtl/verilog/de10-nano_nanorv32_wb_soc_qqspi.v
source src/de10-nano-nanorv32-wb-soc-qqspi_0/data/de10-nano-pinmap.tcl
source src/de10-nano-nanorv32-wb-soc-qqspi_0/data/options.tcl
set_global_assignment -name SDC_FILE src/de10-nano-nanorv32-wb-soc-qqspi_0/data/de10-nano.sdc
set_global_assignment -name SEARCH_PATH ../src/uart16550
set_global_assignment -name SEARCH_PATH ../src/wb_bfm
set_global_assignment -name SEARCH_PATH ../src/serv_soc_wb
