// THIS FILE IS AUTOGENERATED BY wb_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
`default_nettype none
module wb_intercon
   (input  wire        wb_clk_i,
    input  wire        wb_rst_i,
    input  wire [31:0] wb_serv_adr_i,
    input  wire [31:0] wb_serv_dat_i,
    input  wire  [3:0] wb_serv_sel_i,
    input  wire        wb_serv_we_i,
    input  wire        wb_serv_cyc_i,
    input  wire        wb_serv_stb_i,
    input  wire  [2:0] wb_serv_cti_i,
    input  wire  [1:0] wb_serv_bte_i,
    output wire [31:0] wb_serv_rdt_o,
    output wire        wb_serv_ack_o,
    output wire        wb_serv_err_o,
    output wire        wb_serv_rty_o,
    output wire [31:0] wb_qqspi0_adr_o,
    output wire [31:0] wb_qqspi0_dat_o,
    output wire  [3:0] wb_qqspi0_sel_o,
    output wire        wb_qqspi0_we_o,
    output wire        wb_qqspi0_cyc_o,
    output wire        wb_qqspi0_stb_o,
    output wire  [2:0] wb_qqspi0_cti_o,
    output wire  [1:0] wb_qqspi0_bte_o,
    input  wire [31:0] wb_qqspi0_rdt_i,
    input  wire        wb_qqspi0_ack_i,
    input  wire        wb_qqspi0_err_i,
    input  wire        wb_qqspi0_rty_i,
    output wire [31:0] wb_uart0_adr_o,
    output wire  [7:0] wb_uart0_dat_o,
    output wire  [3:0] wb_uart0_sel_o,
    output wire        wb_uart0_we_o,
    output wire        wb_uart0_cyc_o,
    output wire        wb_uart0_stb_o,
    output wire  [2:0] wb_uart0_cti_o,
    output wire  [1:0] wb_uart0_bte_o,
    input  wire  [7:0] wb_uart0_rdt_i,
    input  wire        wb_uart0_ack_i,
    input  wire        wb_uart0_err_i,
    input  wire        wb_uart0_rty_i,
    output wire [31:0] wb_gpio0_adr_o,
    output wire [31:0] wb_gpio0_dat_o,
    output wire  [3:0] wb_gpio0_sel_o,
    output wire        wb_gpio0_we_o,
    output wire        wb_gpio0_cyc_o,
    output wire        wb_gpio0_stb_o,
    output wire  [2:0] wb_gpio0_cti_o,
    output wire  [1:0] wb_gpio0_bte_o,
    input  wire [31:0] wb_gpio0_rdt_i,
    input  wire        wb_gpio0_ack_i,
    input  wire        wb_gpio0_err_i,
    input  wire        wb_gpio0_rty_i,
    output wire [31:0] wb_tmr0_adr_o,
    output wire [31:0] wb_tmr0_dat_o,
    output wire  [3:0] wb_tmr0_sel_o,
    output wire        wb_tmr0_we_o,
    output wire        wb_tmr0_cyc_o,
    output wire        wb_tmr0_stb_o,
    output wire  [2:0] wb_tmr0_cti_o,
    output wire  [1:0] wb_tmr0_bte_o,
    input  wire [31:0] wb_tmr0_rdt_i,
    input  wire        wb_tmr0_ack_i,
    input  wire        wb_tmr0_err_i,
    input  wire        wb_tmr0_rty_i);

wire [31:0] wb_resize_uart0_adr;
wire [31:0] wb_resize_uart0_dat;
wire  [3:0] wb_resize_uart0_sel;
wire        wb_resize_uart0_we;
wire        wb_resize_uart0_cyc;
wire        wb_resize_uart0_stb;
wire  [2:0] wb_resize_uart0_cti;
wire  [1:0] wb_resize_uart0_bte;
wire [31:0] wb_resize_uart0_rdt;
wire        wb_resize_uart0_ack;
wire        wb_resize_uart0_err;
wire        wb_resize_uart0_rty;

wb_mux
  #(.num_devices (4),
    .MATCH_ADDR  ({32'h00000000, 32'h90000000, 32'h91000000, 32'hfffffff0}),
    .MATCH_MASK  ({32'hfe000000, 32'hfffffff8, 32'hffffffe0, 32'hfffffff0}))
 wb_mux_serv
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_serv_adr_i),
    .wbm_dat_i (wb_serv_dat_i),
    .wbm_sel_i (wb_serv_sel_i),
    .wbm_we_i  (wb_serv_we_i),
    .wbm_cyc_i (wb_serv_cyc_i),
    .wbm_stb_i (wb_serv_stb_i),
    .wbm_cti_i (wb_serv_cti_i),
    .wbm_bte_i (wb_serv_bte_i),
    .wbm_dat_o (wb_serv_rdt_o),
    .wbm_ack_o (wb_serv_ack_o),
    .wbm_err_o (wb_serv_err_o),
    .wbm_rty_o (wb_serv_rty_o),
    .wbs_adr_o ({wb_qqspi0_adr_o, wb_resize_uart0_adr, wb_gpio0_adr_o, wb_tmr0_adr_o}),
    .wbs_dat_o ({wb_qqspi0_dat_o, wb_resize_uart0_dat, wb_gpio0_dat_o, wb_tmr0_dat_o}),
    .wbs_sel_o ({wb_qqspi0_sel_o, wb_resize_uart0_sel, wb_gpio0_sel_o, wb_tmr0_sel_o}),
    .wbs_we_o  ({wb_qqspi0_we_o, wb_resize_uart0_we, wb_gpio0_we_o, wb_tmr0_we_o}),
    .wbs_cyc_o ({wb_qqspi0_cyc_o, wb_resize_uart0_cyc, wb_gpio0_cyc_o, wb_tmr0_cyc_o}),
    .wbs_stb_o ({wb_qqspi0_stb_o, wb_resize_uart0_stb, wb_gpio0_stb_o, wb_tmr0_stb_o}),
    .wbs_cti_o ({wb_qqspi0_cti_o, wb_resize_uart0_cti, wb_gpio0_cti_o, wb_tmr0_cti_o}),
    .wbs_bte_o ({wb_qqspi0_bte_o, wb_resize_uart0_bte, wb_gpio0_bte_o, wb_tmr0_bte_o}),
    .wbs_dat_i ({wb_qqspi0_rdt_i, wb_resize_uart0_rdt, wb_gpio0_rdt_i, wb_tmr0_rdt_i}),
    .wbs_ack_i ({wb_qqspi0_ack_i, wb_resize_uart0_ack, wb_gpio0_ack_i, wb_tmr0_ack_i}),
    .wbs_err_i ({wb_qqspi0_err_i, wb_resize_uart0_err, wb_gpio0_err_i, wb_tmr0_err_i}),
    .wbs_rty_i ({wb_qqspi0_rty_i, wb_resize_uart0_rty, wb_gpio0_rty_i, wb_tmr0_rty_i}));

wb_data_resize
  #(.aw     (32),
    .mdw    (32),
    .sdw    (8),
    .endian ("little"))
 wb_data_resize_uart0
   (.wbm_adr_i (wb_resize_uart0_adr),
    .wbm_dat_i (wb_resize_uart0_dat),
    .wbm_sel_i (wb_resize_uart0_sel),
    .wbm_we_i  (wb_resize_uart0_we),
    .wbm_cyc_i (wb_resize_uart0_cyc),
    .wbm_stb_i (wb_resize_uart0_stb),
    .wbm_cti_i (wb_resize_uart0_cti),
    .wbm_bte_i (wb_resize_uart0_bte),
    .wbm_dat_o (wb_resize_uart0_rdt),
    .wbm_ack_o (wb_resize_uart0_ack),
    .wbm_err_o (wb_resize_uart0_err),
    .wbm_rty_o (wb_resize_uart0_rty),
    .wbs_adr_o (wb_uart0_adr_o),
    .wbs_dat_o (wb_uart0_dat_o),
    .wbs_we_o  (wb_uart0_we_o),
    .wbs_cyc_o (wb_uart0_cyc_o),
    .wbs_stb_o (wb_uart0_stb_o),
    .wbs_cti_o (wb_uart0_cti_o),
    .wbs_bte_o (wb_uart0_bte_o),
    .wbs_dat_i (wb_uart0_rdt_i),
    .wbs_ack_i (wb_uart0_ack_i),
    .wbs_err_i (wb_uart0_err_i),
    .wbs_rty_i (wb_uart0_rty_i));

    assign wb_uart0_sel_o = 0;
endmodule
